version: '3'

services:
  nginx:
    # container_name: nginx-server
    image: nginx
    stdin_open: true
    tty: true
    restart: always
    network_mode: host
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - app_data:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt

  coturn:
    image: instrumentisto/coturn
    # container_name: coturn
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./turnserver.conf:/etc/coturn/turnserver.conf

  spreedbackend:
    build: .
    volumes:
      - ./server.conf:/config/server.conf
    network_mode: host
    restart: unless-stopped
    depends_on:
      - nats
      - janus
      - coturn

  nats:
    image: nats:2.1
    volumes:
      - ./gnatsd.conf:/config/gnatsd.conf
    command: ["-c", "/config/gnatsd.conf"]
    network_mode: host
    restart: unless-stopped

  janus:
    build: docker/janus
    command: ["janus"]
    network_mode: host
    restart: unless-stopped

volumes:
  app_data: